#!/bin/sh
pass=0
fail=0
i=1
while [ $i -le 6 ]
do
	echo "Enter the cie and see marks(out of 50 for see) of the sub$i "
	read cie see
	total=`expr $cie+$see|bc`
	case $total in
		100) echo "S grade "
			pass=$((pass+1)) ;;
		9[0-9]) echo "S grade "
			pass=$((pass+1)) ;;
		8[0-9]) echo "A grade "
			pass=$((pass+1)) ;;
		7[0-9]) echo "B grade "
			pass=$((pass+1)) ;;
		6[0-9]) echo "C grade "
			pass=$((pass+1)) ;;
		5[0-9]) echo "D grade "
			pass=$((pass+1)) ;;
		4[0-9]) echo "E grade "
			pass=$((pass+1)) ;;
		[0123][0-9]) echo "F grade "
			fail=$((fail+1)) ;;
		*)echo "error in input"
	esac
	i=$((i+1))
done
echo -e "no of sub passed : $pass\nno of subjects failed $fail\n"
