#!/bin/sh
echo "Enter the year "
read year
if [ $((year%400)) -eq 0 ] 
then 
	echo "It's a leap year"
elif [ $((year%4)) -eq 0 ] 
then 
	if [ $((year%100)) -eq 0 ] 
	then 
		echo "It's a non leap year"
	else
		echo "It's a leap year "
	fi
else
	echo "It's a non leap year "
fi
